#ifndef SYNTAX_H_INCLUDED
#define SYNTAX_H_INCLUDED

enum TOKEN_TYPE
{
    CONSTANT,
    VARIABLE,
    FUNCTION,
    FUNC_CALL_PARAMETER,
    OPERATOR
};

const char CONSTANT_NAME[]  = "constant";

#endif // SYNTAX_H_INCLUDED
